// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBrJphiF_Jy06oFDH2PcYrABJImkq_Jc',
    appId: '1:1086825193312:web:198ff5c93a4df0b5410805',
    messagingSenderId: '1086825193312',
    projectId: 'agentic-mafia',
    authDomain: 'agentic-mafia.firebaseapp.com',
    storageBucket: 'agentic-mafia.firebasestorage.app',
    measurementId: 'G-W97YY25SH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcGSQuPCLQc-gpixD7XJ8aG7roJKgojM',
    appId: '1:1086825193312:android:dec5f7337f866e98410805',
    messagingSenderId: '1086825193312',
    projectId: 'agentic-mafia',
    storageBucket: 'agentic-mafia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv8nh5dAEdcXK9xnABHOa14wtUfLsT9MU',
    appId: '1:1086825193312:ios:b32f4a41b39adb82410805',
    messagingSenderId: '1086825193312',
    projectId: 'agentic-mafia',
    storageBucket: 'agentic-mafia.firebasestorage.app',
    iosBundleId: 'com.example.agenticMafia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv8nh5dAEdcXK9xnABHOa14wtUfLsT9MU',
    appId: '1:1086825193312:ios:b32f4a41b39adb82410805',
    messagingSenderId: '1086825193312',
    projectId: 'agentic-mafia',
    storageBucket: 'agentic-mafia.firebasestorage.app',
    iosBundleId: 'com.example.agenticMafia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwBrJphiF_Jy06oFDH2PcYrABJImkq_Jc',
    appId: '1:1086825193312:web:2c321d224f340c3c410805',
    messagingSenderId: '1086825193312',
    projectId: 'agentic-mafia',
    authDomain: 'agentic-mafia.firebaseapp.com',
    storageBucket: 'agentic-mafia.firebasestorage.app',
    measurementId: 'G-9KRD41G46Q',
  );
}
